### ISSUE TITLE
👋Congrats with EuRuKo 2019!

### ISSUE THREAD

**Issue by bai** [euruko/euruko2019.github.io#1]
🎉

**Comment by bai** [comment]
I've pointed `euruko2019.org` DNS to this github repo: https://euruko2019.org/ — let me know if you want me to set it up differently 💯

**Comment by FloorD** [comment]
@bai Ray' and I would love to use euruko.org email addresses for our sponsor outreach. Is this something we can solve ourselves, or what do you need from our side to create these?

**Comment by bai** [comment]
Hey @FloorD, I just sent you an email.

**Comment by FloorD** [comment]
awesome, thanks!
