### ISSUE TITLE
Provide links to the vimeo videos on the website.

### ISSUE THREAD

**Issue by coalwater** [euruko/euruko2019.github.io#36]
In the conference it was mentioned a lot of times that the videos are live and that they are available at http://euruko2019.org/.
Today I told a colleague that they can watch the videos on the website and when I opened it the videos were gone and there was no mention of how to find the videos.

I did some googling and that's how I found my way here, also I got the links for the two days from the commit history.

It would be nice if we ( or I could do that ) add links to the 2 videos so people could still benefit from it.

To make it easier for whom ever is going to work on this, here's the two links

day 1: https://vimeo.com/341960959
day 2: https://vimeo.com/341962973

Note: For some reason the day 1 video only includes the keynote, but not the rest of the day, is there another video for the talks for day 1 ?

**Comment by tombruijn** [comment]
Hi @coalwater ,

We're going to put the videos on youtube on our EuRuKo 2019 channel.
Every talk will be split up in its own video.

We'll tweet about it for sure: https://twitter.com/euruko

**Comment by coalwater** [comment]
That would be amazing.
Thanks

**Comment by tombruijn** [comment]
They're live at: https://www.youtube.com/channel/UCWcOB8yVZDoPGdbvq8HR6IQ/videos
