### ISSUE TITLE
EuRuKo Start-up contest information and rules

### ISSUE THREAD

**Issue by tombruijn** [euruko/euruko2019.github.io#9]
Hello there 👋 

Want to participate in the EuRuKo 2019 start-up contest? Great!
Please read the contest description and rules below first.

When you're all up to speed, create a new issue on this (public) repository using the "new issue" button at the top of this issue on the right with your entry for the contest, or send an email to organisers@euruko.org with the topic "Start-up contest entry".

## Description

People visit EuRuKo and other conferences not just for the amazing talks, but for the people! Meeting new people and reconnecting with your long lost conference BFFs are very much part of the experience.

But it's not easy for everyone. Based on surveys from previous EuRuKo editions we've learned that while many people come to make new friends, not all are successful in doing so.

To help this years EuRuKo attendees we want ideas for getting people together. EuRuKo 2019's "Start-up contest" is the way for fresh start-ups to show what they can do. Send in your brilliant idea to get people talking and **win** your own EuRuKo booth!

Join our dashing sponsors on the booth floor and get your name out there!

## Examples

Listed below are some examples of entries for this contest. Small in scope and built with the purpose of creating engagement between conference attendees. These are just ideas, feel free to iterate on them or come up with completely fresh ideas!

- A public events board where people can submit game nights, jam sessions, meetups at bars or other locations, etc.
- Set up a game night where people are set up in random teams where they have to work together. 
- A polling app for user generated polls about talks, events and other subjects.
- A treasure hunt aboard the SS Rotterdam!
- Short (5-10) minute workshops to learn conversations starters or do short improvisation sessions to learn how to introduce oneself.

## Contest rules

- Participants need to be a start-up. Our definition of a start-up is as follows:
    - Company size in employees: 1-20 employees
    - Years in operation: A maximum of 3 years
    - Funding: Bootstrapped or pre-funding stage
- Participants need to be able to build their entry themselves.
    - If any kind of app/website or other technical work needs to be done, the participants need to be able to build the end-result themselves.
    - If needed, the conference will provide some help with project management.
- The entry needs to be built in the allocated time (see timeline below), allowing for around two weeks of beta testing if needed. (6 weeks in total)
- The entries that wins the start-up package (worth € 5000) receive the following:
    - The winners are offered a 1 table booth for the duration of the conference.
    - The winners will receive a Silver sponsor package with all its benefits.
    - A flyer will be added to the conference goodie bag to distribute or promote the contest's end result (app or otherwise).
- Participants need to have to have something to showcase at their booth.
    - Their company, product or service.
- The fine print:
    - At minimum this contest needs 3 entries for its kick-off.
    - The EuRuKo organizers are free to alter the contest rules at any time within reason, in order to prevent unfair competition.

## Contest timeline

- 03 May:  Entries close
- 10 May:  Winners announced. Time to get building!
- 05 June: Beta testing starts (if needed)
- 21 June: Conference starts

## Project requirements

- The project creates a way for conference attendees to meet one another and engage in a conversation. It breaks the ice between complete strangers.
- It creates more engagement between attendees at the venue and/or outside of it.
- It creates a safe environment for all users to share their thoughts and opinions.
- It adheres to our Code of Conduct: https://euruko2019.org/#code-of-conduct

### Technical requirements

- The contest's winning entry will be released under an open source license so it's reusable by other EuRuKo editions and conferences.
- Easily maintainable. Preferably no native app requirements without anyone being able to maintain or take ownership of them (think: app stores).
- If the project involves user generated content, conference organizers can manage the content on the system to remove anything that violates the Code of Conduct.
- Obviously privacy and security are of utmost importance. We are at our most vulnerable when we're out of town, surrounded by people we don't yet know. GDPR compliance is a must.

## Changes

- 2019-01-29: First version.

**Comment by raytalks** [comment]
Booth is 2x2m not 3x3 (we only have 2 of those and they're reserved for our Platinum sponsors).
